"""Turn a failed CaseResult into a pasteable GitHub IssueDraft (T5)."""

from __future__ import annotations

from .probe import CaseResult


def to_issue_draft(result: CaseResult) -> dict:
    """Build ``{title, body}`` from a CaseResult.

    Empty issues are forbidden: title and body must include ``case_id`` and
    non-empty expected/actual/repro content.
    """
    if not result.case_id.strip():
        raise ValueError("CaseResult.case_id must be non-empty for IssueDraft")
    if result.ok:
        raise ValueError(
            f"to_issue_draft refuses successful case {result.case_id!r}; "
            "IssueDraft is only for failures"
        )

    expected = (result.expected or "").strip()
    actual = (result.actual or "").strip()
    logs = (result.logs or "").strip()
    steps = [s.strip() for s in result.repro_steps if isinstance(s, str) and s.strip()]

    if not expected or not actual:
        raise ValueError(
            f"CaseResult {result.case_id!r} missing expected/actual; refuse empty IssueDraft"
        )
    if not steps:
        raise ValueError(
            f"CaseResult {result.case_id!r} missing repro_steps; refuse empty IssueDraft"
        )

    title = f"[ACP Host Probe] {result.case_id} failed"
    body_parts = [
        f"## Case `{result.case_id}`",
        "",
        "Host-like ACP subprocess probe reported a failure. "
        "This draft is generated by `tests/acp_host` — do not treat it as a "
        "product fix; open/triage as needed.",
        "",
        "### Expected",
        "",
        expected,
        "",
        "### Actual",
        "",
        actual,
        "",
        "### Repro steps",
        "",
    ]
    for i, step in enumerate(steps, 1):
        body_parts.append(f"{i}. {step}")
    body_parts.extend(["", "### Logs / stderr tail", "", "```", logs or "(no logs captured)", "```", ""])
    body = "\n".join(body_parts)
    if not body.strip() or result.case_id not in body:
        raise ValueError("refuse empty IssueDraft")
    return {"title": title, "body": body}
